edm:
  jwt:
    secret: 69u5CaneBXhzhTgHCGBa0gUf6Q5P7CVk
    expiration: 3600000
  core:
    credentials:
      email: EDM-CORE@EDM.COM
      password: EDM-CORE111
  api:
    url: http://localhost:8080
    credentials:
      email: EDM-API@EDM.COM
      password: EDM-API111
  schedule:
    min-employees: 2
    max-employees: 4
    ratio-weight: 5
    min-working-hours: 2
server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db